name: Vulnerability checks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Bandit vulnerability scanner
        uses: StefanFl/secobserve_github_actions/SAST/bandit@main
        with:
          target: 'dd_import'
          report_name: 'dd_import_bandit.sarif'
      - name: Run Semgrep vulnerability scanner
        uses: StefanFl/secobserve_github_actions/SAST/semgrep@main
        with:
          target: 'backend'
          report_name: 'semgrep_backend.json'
          configuration: 'r/python'
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: secobserve
          path: |
            dd_import_bandit.sarif
            semgrep_backend.json
